apiVersion: apps/v1
kind: Deployment
metadata:
  name: JspMavenDemo
  labels:
    app: JspMavenDemo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: JspMavenDemo
  template:
    metadata:
      labels:
        app: JspMavenDemo
    spec:
      containers:
      - name: JspMavenDemo
        image: devops-poc/jsp:1.0.0
        ports:
        - containerPort: 80
